name: 'Build Checks'

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  lint-checks:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Run Check
        run: yarn app:check
